### ISSUE TITLE
Fix and continue work on Blue game.

### ISSUE THREAD

**Issue by seisatsu** [seisatsu/Driftwood#102]
The test world we currently use doesn't behave as expected in some areas, and is also really short and lacking.

**Comment by pmer** [comment]
Another puzzle :) involving the interact button. For fun.

**Comment by seisatsu** [comment]
Created a github project for this.

**Comment by pmer** [comment]
Where?

**Comment by pmer** [comment]
I found it at https://github.com/seisatsu/Driftwood/projects/1
