### ISSUE TITLE
Release an EXE for Windows.

### ISSUE THREAD

**Issue by seisatsu** [seisatsu/Driftwood#103]
Our audience may be severely limited by the number of prospective users having only a little knowledge about Python. Installing Driftwood on Windows is too hard. There are utilities that convert a Python program and all its dependencies into a single Windows executable. Let's try it.

https://pypi.python.org/pypi/py2exe/0.9.2.0/

**Comment by pmer** [comment]
I'll have a Windows computer in a month, perhaps, and can take a look at this if it's not done by then.

**Comment by seisatsu** [comment]
I have one, so I'll work on it.

**Comment by seisatsu** [comment]
Attached a binary package to Alpha-0.0.5 release, compiled with Pyinstaller and Python 3.5.3. It has been tested on Windows 10 so far. Need to make sure it works on other versions, otherwise make multiple releases.

**Comment by seisatsu** [comment]
Since I have the process for doing this worked out, I will close this issue and document it later.
