### ISSUE TITLE
Crash from cache purging in-use resources

### ISSUE THREAD

**Issue by pmer** [seisatsu/Driftwood#111]
The cache purges all resources after a set timeout, even if they are still in use. The cache calls the resources' `_terminate()` which in turn calls `CacheManager.reverse_purge`, leading to the resource getting removed from the cache twice which crashes.

Also,

- The music stops playing. AudioManager thinks the music finished, so tries to `_terminate()` the music a third time.
- All images get `Invalid texture` errors on SDL_RenderCopy and the game exits since a frame failed to draw correctly.

**Comment by pmer** [comment]
My first thought here is that we can maintain a reference count cache-able objects and then we call `_terminate()` when the last reference is up. But to do this, we need to make sure we deref cache-able objects held by any Python object, which means we need to be able to run code on every single object's destructor. But we know CPython doesn't support this so that's not feasible.

**Comment by pmer** [comment]
What have other PySDL games done?

**Comment by seisatsu** [comment]
Good question. There is actually not a very big PySDL2 community.
