### ISSUE TITLE
Remove TPS support

### ISSUE THREAD

**Issue by pmer** [seisatsu/Driftwood#112]
Since we do one tick per frame, we will rely on vsync to manage our tick rate for now.

See #96 for details.

**Comment by seisatsu** [comment]
That uses unnecessary CPU cycles. Have you seen how much CPU Driftwood can eat up at higher tps? I think we should keep the setting.

**Comment by pmer** [comment]
@seisatsu I haven't because it runs with vsync on my computer.

Does your vsync not work?

**Comment by pmer** [comment]
Actually, hold on a second. I haven't tested Driftwood with no TPS limit yet, and I am *assuming* it limits itself to one tick per frame.

Let me check this assumption.

**Comment by pmer** [comment]
If possible, if Driftwood it isn't using vsync on your computer, I'd rather open an issue and fix that as a bug.

**Comment by seisatsu** [comment]
One frame, one tick. And the ticks run at exactly the tps given, unless obstructed by load.

**Comment by pmer** [comment]
If I set the TPS and FPS to 6000, the game still only runs at 60 TPS and 60 FPS on my Mac.

Looks like even with common Linux setups we can't expect this behavior, though. We'll need to keep TPS. I might try to improving the current TPS system sometime.

**Comment by pmer** [comment]
Here is the behavior I was expecting with vsync on.

![screen shot 2017-04-19 at 12 05 25 am](https://cloud.githubusercontent.com/assets/107998/25167338/f58c2ca6-2493-11e7-9354-f7fdbec3f75c.png)

**Comment by pmer** [comment]
@seisatsu Please excuse me for bringing up a closed issue, but could you provide some information about what graphics card & driver that computer has?

I just got a Linux with a Radeon setup today & I can't reproduce what you're describing.

![2017-04-20-005038_1920x1080_scrot](https://cloud.githubusercontent.com/assets/107998/25219539/aee67fce-2563-11e7-8b0c-1c3e1fc25c64.png)
