### ISSUE TITLE
Remove Python < 3.5 support?

### ISSUE THREAD

**Issue by seisatsu** [seisatsu/Driftwood#113]
There are places in our code where Python 3.5 syntax is used, breaking support for older versions. Should we change the code to accommodate 3.3.3 again, or change the minimum version to 3.5? I think 3.3.3 is pretty old.

**Comment by pmer** [comment]
macOS comes with Python 2 but not 3. We'll probably package 3 in the application bundle making its distribution similar to Windows.

Thus, this will only affect Linux distros with old Python versions. Any we care about?

**Comment by seisatsu** [comment]
Nope.

**Comment by pmer** [comment]
Sounds good to me!

**Comment by seisatsu** [comment]
Done in 529904f.
