### ISSUE TITLE
Programmatically determine TPS & FPS

### ISSUE THREAD

**Issue by pmer** [seisatsu/Driftwood#115]
Possible starting point with:

- SDL_GetWindowDisplayIndex (for windowed)
- SDL_GetCurrentDisplayMode (for windowed)
- SDL_GetWindowDisplayMode (for fullscreen)

@seisatsu Question. Can we unify TPS & FPS and stop referring to TPS as its own thing?

**Comment by seisatsu** [comment]
Hmm, that could be a good idea. I'd like the ability to limit the fps if we do that though.

**Comment by pmer** [comment]
@seisatsu The display mode will tell us the refresh rate of the monitor, so we can limit the FPS to that.

**Comment by seisatsu** [comment]
The ability to cap your own fps is fairly standard though. Is there a reason we shouldn't allow it?

**Comment by pmer** [comment]
That's true, but you'll notice it's mainly found in state of the art highly-demanding 3D games. 2D games don't have an FPS option very often.

I think they're either to improve visual appearance if your game's frame rate varies wildly depending on which direction you're facing at any point in time (first person shooters, etc) or when you're trying to conserve battery power on laptops (but if we can pull off this 60 FPS limiter Driftwood should use pretty low power already).

**Comment by pmer** [comment]
Anyway, if you want to add an FPS limiter you're definitely welcome.

**Comment by pmer** [comment]
SDL has functions to iterate the display modes of the monitor so you can find the max FPS the monitor supports and you can allow a user to pick a number between 1 and that.
