### ISSUE TITLE
Allow log output to file.

### ISSUE THREAD

**Issue by seisatsu** [seisatsu/Driftwood#121]
In order to solve #89 I will either make a curses setup to show the developer console and the log at the same time, or more likely just show the developer console instead of the log when it's enabled, for the time being. Either solution necessitates the ability to output the log to a file without using command line pipes.

**Comment by pmer** [comment]
@seisatsu Do we still need this with the current implementation of #89?

**Comment by seisatsu** [comment]
Yes, #89 does not affect logging the way I implemented it.
