### ISSUE TITLE
Tileset image paths should be searched for relative to the Tilemap JSON path

### ISSUE THREAD

**Issue by pmer** [seisatsu/Driftwood#126]
If I have a tilemap `areas/my_map.json` that loads a `../tiles/my_tiles.png`, Tiled thinks it resolves to `areas/../tiles/my_tiles.png` but Driftwood thinks it resolves to `../tiles/my_tiles.png`.

**Comment by seisatsu** [comment]
Yes. This is a problem with Tiled always saving paths relative to the current working directory though. I usually remedy this by working from the root directory of the world.

**Comment by pmer** [comment]
I remember doing that on Linux. :) Unfortunately it looks like Tiled on macOS doesn't support that. :(

**Comment by seisatsu** [comment]
Research if anyone else has had this issue.

**Comment by pmer** [comment]
Found a C# Tiled map loader:

https://bitbucket.org/vinull/xtiled/issues/19/external-tileset-directories-are-relative

**Comment by pmer** [comment]
Here is what I have tried:

- Opening a map in Finder with Tiled.
- Starting Tiled and then opening a map with its Open File dialog.
- Running Tiled from the command line, calling its executable directly.

In the first two cases, Tiled will start with its $PWD set to $HOME. In the third its $PWD will be set to the current directory I'm in. However, in all three, I experience the problem related in this issue.

**Comment by pmer** [comment]
This was changed in Tsunagari in 2014. https://github.com/pmer/TsunagariC/commit/bdf693f7

**Comment by pmer** [comment]
For those Linux users who prefer the command line, this change will mean you'll have to launch Tiled with `(cd path/to; tiled map)` instead of `tiled path/to/map`.

**Comment by seisatsu** [comment]
Why not both?

**Comment by pmer** [comment]
Oops, I think I misunderstood your first comment and forgot how Tiled works on Linux.

So nevermind—there is no difference between those two command inocations.
