### ISSUE TITLE
Allow entities with multiple images

### ISSUE THREAD

**Issue by pmer** [seisatsu/Driftwood#127]
Driftwood should allow game authors to represent the graphics for an entity with a composite of several images layered on top of each other. This allows a game to mix-and-match different parts of an entity's graphic together for different combinations.

This saves artists some work. Otherwise they'd have composite the images manually and would need to recomposite them every time they updated one of the constituent parts.

**Comment by seisatsu** [comment]
This will take a small change to entity descriptors and probably less than 20 lines of code.

**Comment by seisatsu** [comment]
Currently, members are defined in a stance in the entity descriptor as a list of member IDs. Let's allow any of those member IDs to instead be a list of member IDs. If a second-layer list is found in the members list when reading the descriptor, those images are layered for that frame.
