### ISSUE TITLE
Entities don't start animating when created

### ISSUE THREAD

**Issue by pmer** [seisatsu/Driftwood#131]
If an entity's init stance is animated, it doesn't start animating when it's first created.

You can call `entity.set_stance("init")` to fix this, but it shouldn't be necessary.

**Comment by pmer** [comment]
Since we're focusing on bugs I'm going to add this to 0.0.7.

**Comment by seisatsu** [comment]
Sorry to take your assignment, but it was due to just a few lines I forgot when originally writing the code way back.

**Comment by pmer** [comment]
Haha, no worries.
