### ISSUE TITLE
Stack trace not showing in script

### ISSUE THREAD

**Issue by pmer** [seisatsu/Driftwood#144]
Just got this exception:

```
Driftwood 2D
Starting up...
[0] INFO: Path: appended: data/castle/
[0] INFO: Path: rebuilt
[0] INFO: Audio: initialized mixer output
[0] INFO: Audio: initialized mixer audio format support: ogg
[0] INFO: Script: loaded: Scripts/map_util.py
[0] INFO: Script: loaded: Entities/__init__.py
[0] ERROR: Script: __load: broken script: init.py: 
Traceback (most recent call last):
TypeError: list indices must be integers or slices, not str
[0] ERROR: Script: no such module: init.py
Shutting down...
```

Not sure where the error is happening, which makes it hard to solve. I think the exception is in some engine code that the script is calling (code that I'm writing that's currently buggy).

**Comment by seisatsu** [comment]
Weird. See if 6fa0d13 fixed it. I also updated the error messages to be less rude.

**Comment by seisatsu** [comment]
It would help if I knew the crash conditions.

**Comment by pmer** [comment]
Oh, there's nothing special about the *particular* error I was getting. To replicate just introduce any error into the code that throws and exception. Or raise one manually for test purposes.

I'll test in a bit!

**Comment by pmer** [comment]
Looks like it's not fixed yet.

## To reproduce

```python
# init.py
Driftwood.script.register(None, None)
```

```python
# scriptmanager.py

class ScriptManager
    def register(self, event, func):
        def f():
            o = []
            o[3]
        f()
```

## What I see

```
[0] ERROR: Script: __load: error from script: init.py: 
Traceback (most recent call last):
  File "./scriptmanager.py", line 303, in __load
IndexError: list index out of range
[0] ERROR: Script: no such module: init.py
```

## What I expect

A traceback that includes the call to `register` and its own call to `f`. `f` is just there to test the stack trace. It should definitely show.

**Comment by seisatsu** [comment]
Hm. Maybe because it's failing inside ScriptManager it's tripping up that system. I'll poke around.

**Comment by seisatsu** [comment]
This reproduction isn't very helpful to me because it's new code. Can you make our engine crash this way and then give me the script that did it?

**Comment by pmer** [comment]
Sure thing!

Can you try this:

```
$ git fetch
$ git checkout pmer/artificial-error
$ make
$ bin/driftwood
```

It's a branch that contains the edits in my reproduction. Read 03c75f540ea540bc5c6244db80a5c4aa378706bc. It induces an artificial exception to test the behavior of our exception handling.

**Comment by pmer** [comment]
\o/
