### ISSUE TITLE
Return object ID instead of instance from managers.

### ISSUE THREAD

**Issue by seisatsu** [seisatsu/Driftwood#149]
In managers which keep a registry of their managed objects by ID, a method to create a new object should return the ID instead of the object instance.

**Comment by seisatsu** [comment]
Expand this to lookup methods as well. I think we have some inconsistencies.

**Comment by pmer** [comment]
See `EntityManager.layer()` versus `LightManager.layer()`

**Comment by pmer** [comment]
Oops nevermind.

**Comment by pmer** [comment]
So instead of being returned an object and then calling one of its methods, you'll call a method on its manager and pass the id?

I was thinking of moving Tsunagari in this direction as well, but haven't made a lot of progress on it yet. :)

**Comment by seisatsu** [comment]
Yes, ideally the engine should never return an object except internally.

**Comment by pmer** [comment]
Wow, that was easier than I expected!

**Comment by seisatsu** [comment]
Yeah me too. I expected it to take longer than 5 minutes for some reason.
