### ISSUE TITLE
Large simple worlds load slowly.

### ISSUE THREAD

**Issue by seisatsu** [seisatsu/Driftwood#157]
It can take over a second for a particularly large world to load to screen, even if the world is simple. The new uitest world introduced in 040a555c81c341fe08e2c40758729fca770bc505 loads slowly, even though it only has two tile graphics and no player. I suspect that we need to support graphical occlusion to fix this.

**Comment by pmer** [comment]
Would graphical occlusion really have an effect on area load times? I can see how it would speed up rendering each frame, but...

**Comment by pmer** [comment]
Here's an outland-ish idea. If the engine was capable of storing most of the boring, repetitive tiles as *just* a `gid` with no associated `Tile` object, area loads would be lightning fast. The engine would be able to avoid a whole lot of malloc calls and object instantiations that it's doing right now. Thousands, in fact.

It might replace this code: https://github.com/seisatsu/Driftwood/blob/c9552b2586999b6ea37d06cebfc325c721e0b141/src/layer.py#L242-L253

which creates new Python objects in a loop, with perhaps a single assignment statement:

```python
self.tiles = self.__layer["data"]
```

Thus reducing layer processing from O(n) to O(1) in the number of tiles in that layer.

**Comment by seisatsu** [comment]
That's more or less what I meant by occlusion. Maybe I used the wrong word.

**Comment by seisatsu** [comment]
I guess the Layer class could store all of the tile information in a dict, and the Tile class methods could be reworked as lambdas.

**Comment by seisatsu** [comment]
For now, c8542ef uses a Python feature called __slots__ to decrease load for classes expected to be instantiated hundreds or thousands of times. This has decreased area loading time by ~40% on the uitest world. The tradeoff is that new attributes can't be added to the instances at runtime, but we won't need this anyway. I don't think there are other classes currently that would benefit from __slots__.

**Comment by pmer** [comment]
Nice work!

**Comment by seisatsu** [comment]
So, currently Layer contains a list called tiles, which is a list of Tile classes. Instead, we could make tiles a class which mimics the current setup by having a ```__getitem__``` method that constructs a Tile class instance on an as-needed basis, and then caches it for later. The performance gains will be even greater once occlusion works on the first frame.

**Comment by pmer** [comment]
I like that.

Okay, this issue is now blocking on #165.
