### ISSUE TITLE
Calling Driftwood.log.msg() with non-string arguments in a world's init.py causes the game to shutdown & exit

### ISSUE THREAD

**Issue by pmer** [seisatsu/Driftwood#160]
Expected result:

It should print an error w/stack trace and continue.

**Comment by pmer** [comment]
Or it could just convert the argument to a string and continue w/no stack trace. That would be fine, too.

**Comment by seisatsu** [comment]
Any call to msg() causes the game to exit. msg() is for error messages. :) If you turn off halting this won't happen.

This did however help me to find an unrelated crash condition.
