### ISSUE TITLE
Widget loader variable support

### ISSUE THREAD

**Issue by seisatsu** [seisatsu/Driftwood#167]
The STDLib JSON widget loader needs to support passing variables, so that widget descriptors can be used like templates.

A variable looks like "${name}". When loading the widget descriptor, a dictionary of variable names and value correspondences is passed to the loader function. The variables are replaced with their values before the widget is inserted.

**Comment by pmer** [comment]
What about [jinja2](http://jinja.pocoo.org/)? Even though it claims to be designed for generating HTML, it's really just about passing variables into plain-text templates so will work for JSON or any other text-based format. Bonus: we also get if-statements and for-loops.

There might be the possibility that jinja2 is faster than anything we'd write. To quote them:

> High performance with just in time compilation to Python bytecode. Jinja2 will translate your template sources on first load into Python bytecode for best runtime performance.

> Optional ahead-of-time compilation

**Comment by pmer** [comment]
Here's a jinja2 JSON template:

```
{
  "container": {
    "background": "textbox.png",
    "x-center": true,
    "y-below": 8,
    "width": 144,
    "height": 48,
    "members": [
      {
        "text": {
          "contents": "{% contents %}",
          "font": "pf_arma_five.ttf",
          "size": 8,
          "padding": 4,
          "color": "000000FF",
          "wrap": true
        }
      }
    ]
  }
}
```

**Comment by seisatsu** [comment]
I've looked into Jinja2 for another project, sounds like it could work great and we could probably use it other places in the project later on.
