### ISSUE TITLE
Widget loader text wrapping, line-height, and justify

### ISSUE THREAD

**Issue by seisatsu** [seisatsu/Driftwood#168]
Support a "wrap" setting in widget files that is a dictionary containing options for number of characters to wrap after and line spacing.

**Comment by seisatsu** [comment]
Add the following properties to text widgets:

* wrap
* line-height

"wrap" contains the maximum number of characters to show on each line, and "line-height" is a positive or negative value to be added to their vertical separation, the default being zero, directly adjacent.

These need to be implemented in pre-processing, before images are generated from the text.

**Comment by pmer** [comment]
Limiting all lines to a uniform character length won't look good with proportional-width fonts.

What about using [TTF_SizeUTF8](https://www.libsdl.org/projects/SDL_ttf/docs/SDL_ttf.html#SEC40)?

**Comment by pmer** [comment]
I think line-height would benefit if it were specified as a multiple of the current font size.

E.g., `{ line-height: 2.0 }` would be double spaced.

**Comment by seisatsu** [comment]
I implemented a line-spacing property in 605dcd6ad9d58a5255debb32b660622c5bc70341 which uses pixels. "line-height" will be a separate property which uses a multiple of the current font size.

**Comment by seisatsu** [comment]
Added line-height in 8ec4597a9c54bf379f51afb47a8afd0685ff4c22.

**Comment by pmer** [comment]
Nice.

That just leaves "wrap" and "justify" for this issue.

**Comment by seisatsu** [comment]
"wrap" property added in 80feb76d6aa460b47eb5fece762a541852395742.

**Comment by seisatsu** [comment]
The "justify" property was added in 984a269.
