### ISSUE TITLE
Widget loader reference-relative positions

### ISSUE THREAD

**Issue by seisatsu** [seisatsu/Driftwood#169]
Widget components in a widget file should have options to be placed at a position relative to a reference position, for example, so many pixels from the bottom of the screen. We might call this option "bottom" instead of "y", and only allow one or the other to be present.

**Comment by pmer** [comment]
For your information, [CSS uses the same name for its version of this property](https://developer.mozilla.org/en-US/docs/Web/CSS/bottom). 👍

**Comment by seisatsu** [comment]
Properties to be implemented for all widget types:

* top
* bottom
* left
* right

Each places the named side of the target widget w pixels away from the named side of its parent. The parent may be the viewport. Some math will be required when calculating for bottom or right, while top or left simply involve adding w to the x or y value of the widget. Bottom or right calculations require the height or width of the target widget, which may be undetermined until the widget is created. Therefore, these should be implemented in postprocessing, after the widget is created but before the next frame.

**Comment by seisatsu** [comment]
This objective is completed with the addition of the "align" property in bd6c273, which does the jobs of top, bottom, left, right, and justify in one property.
