### ISSUE TITLE
Long hallway in Blue World is mostly black.

### ISSUE THREAD

**Issue by seisatsu** [seisatsu/Driftwood#175]
The lower portion of the long hallway behind the hidden door in Blue World is all black. This occurred before my TileManager update, though it was when I noticed it. @pmer I suspect this could trace back to your occlusion code. Please take a look.

**Comment by seisatsu** [comment]
Confirmed with bisect that the bug was introduced in 84db38802bc5fc6adc60dc62383bfb9e9d7319c4.

**Comment by pmer** [comment]
Alright, I'll take a look!

**Comment by pmer** [comment]
Fixed in a2fa220de21f9930d760d3ed119e22da41ada08a.
