### ISSUE TITLE
Subpixel rendering

### ISSUE THREAD

**Issue by pmer** [seisatsu/Driftwood#35]
To make 64 pixels per second appear smooth on a 60 frame per second display, we need to use subpixel rendering.

Does SDL even support this?

**Comment by seisatsu** [comment]
SDL does not support this. We'd have to use OpenGL.

**Comment by pmer** [comment]
Actually, if the player moved at 60 pixels per second, or some nice rational number (2, 1½, 1⅓, etc) times 60, it should also fix this issue.

**Comment by seisatsu** [comment]
Unfortunately entities are each allowed to move at their own speed, so this is unrealistic. It's probably not feasible to do anything about this until we're ready to try switching to an OpenGL backend for drawing.

**Comment by seisatsu** [comment]
This is basically impossible unless we switch to OpenGL rendering, which isn't happening in the foreseeable future. Closing.

**Comment by pmer** [comment]
This is what Gosu does.
