### ISSUE TITLE
Validate all inputs

### ISSUE THREAD

**Issue by seisatsu** [seisatsu/Driftwood#43]
There are dozens of possible typos that could crash the engine. All inputs need to be validated.

**Comment by pmer** [comment]
Could you describe which inputs should be validated?

**Comment by seisatsu** [comment]
I mean all of the JSON files.

**Comment by seisatsu** [comment]
Entities now validated with jsonschema as of a23c172e902c7285d96c9e2d555d26fdfa5e82c8, config file validated as of d878c4b4e2ccd8ffbf830730b46cafeff756a770.

**Comment by seisatsu** [comment]
Validating map events and triggers as of c97f466531b15c104146610e4d8b81229ce96f33. I think that's it.
