### ISSUE TITLE
Consider moving to an entity-component architecture

### ISSUE THREAD

**Issue by pmer** [seisatsu/Driftwood#45]
It is a superior way to structure video game engines when compared to an object-oriented architecture.
- http://www.richardlord.net/blog/what-is-an-entity-framework
- http://www.richardlord.net/blog/why-use-an-entity-framework

**Comment by seisatsu** [comment]
I'll look into it when I have the energy to read and process those documents. Sounds like a pretty large but possibly worthwhile undertaking.

**Comment by pmer** [comment]
👍

**Comment by pmer** [comment]
Yep, that sounds right.

Getting user-facing features out the door is the most important objective for Driftwood. The entity-component architecture is not a user-facing feature, but it would make it faster and easier to add new user-facing features.

But stopping regular work to make this happen would take time and energy. Let's skip it for at least the short-term.

**Comment by seisatsu** [comment]
I'm closing this for now since I don't plan to do this in the foreseeable future.
