### ISSUE TITLE
Custom Triggers

### ISSUE THREAD

**Issue by seisatsu** [seisatsu/Driftwood#54]
Make it possible for scripts to register custom triggers (exit is a trigger for example) that point to an stdlib or user-defined function. This way the user can conveniently call various functions with simple triggers inserted in the map editor. A bit of syntactical sugar.

**Comment by seisatsu** [comment]
Designing out a sane way to do this turned out to be more difficult than I had originally imagined. Pushing back to Beta-0.1.0.

**Comment by pmer** [comment]
Could you add more description to this feature issue? I am having a hard time understanding what it is.

**Comment by seisatsu** [comment]
It's just a bit of syntactical sugar. Instead of having a map property "on_tile": "something.py,function,arg,arg", you can have "something": "arg,arg" which is triggered during the on_tile event if it exists.

**Comment by pmer** [comment]
Oh, that sounds fun. I might give it a go.

**Comment by seisatsu** [comment]
I'll upload my fork where I had started working on it.

**Comment by seisatsu** [comment]
Look at the custom_triggers branch. I decided to delegate registration of the custom triggers to ScriptManager, but couldn't decide how to integrate it with the map reader.
