### ISSUE TITLE
Review FATAL, ERROR, and WARNING messages/conditions.

### ISSUE THREAD

**Issue by seisatsu** [seisatsu/Driftwood#63]
There may be inconsistent application of the FATAL, ERROR, and WARNING designations in engine messages. Fix these.
- FATAL is raised when the engine absolutely cannot continue in any capacity in its current state. sys.exit(1) is called after all FATAL messages, killing the engine instantly.
- ERROR is raised when a file or script is missing or broken, or an entire manager cannot continue operating in its current state, or to denote a developer error or the failure of a non-critical subsystem.
- WARNING is raised for other problems which do not impede the function of the engine itself but will prevent the current procedure from finishing as expected. Warnings happen in procedures that are expected to fail under certain circumstances.

**Comment by seisatsu** [comment]
Warnings should be for things which are expected to fail sometimes, such as attempting to unregister a tick callback which was already unregistered due to a race condition, or trying to stop a sound effect that finished on its own.

**Comment by pmer** [comment]
Noticed some things were changed in https://github.com/seisatsu/Driftwood/commit/9a7e127fa57e8fe2bde065af7af2f92af6b5eea2. What's left?

**Comment by seisatsu** [comment]
Actually nothing. Since the current stuff seems correct we can just pay attention in the future, and this is done.
