### ISSUE TITLE
Segfault on Mix_FreeMusic

### ISSUE THREAD

**Issue by seisatsu** [seisatsu/Driftwood#70]
We are currently segfaulting on shutdown. <s>This seems to have been introduced during WidgetManager development</s>, and these are almost always caused by a missing or extraneous init, create, or free in an SDL library. Fix this.

It's actually caused during a Mix_FreeMusic call on shutdown. Can't tell why it's breaking.

**Comment by seisatsu** [comment]
Bisect shows the bug was introduced in 37a609577d48c42f485e1b4433632c0b095bf0bc. There's nothing wrong with the code at first glance.

**Comment by pmer** [comment]
@seisatsu: I can't reproduce this on my system. Do you think it might be a Linux thing?

**Comment by seisatsu** [comment]
Fixed in c386c3c6b655e65b24196f19fe48d36643f730bd.
