### ISSUE TITLE
Horrid CPU leak in stdlib flicker code

### ISSUE THREAD

**Issue by seisatsu** [seisatsu/Driftwood#73]
The flicker code in the stdlib creates a massive CPU leak and will freeze up the engine after not that many calls. I suspect it's related to us having to make a hard copy of the function to pass it to tickmanager multiple times. We may want to refactor tickmanager so the same function can have multiple ticks set on it.

**Comment by seisatsu** [comment]
TickManager is confirmed working as expected, and expired flickers are being killed properly. I can't tell yet why the CPU gets consumed.

**Comment by seisatsu** [comment]
Maybe it was introduced in 37a609577d48c42f485e1b4433632c0b095bf0bc just like #70. I'll have to make a test case.

**Comment by pmer** [comment]
How can this be reproduced?

**Comment by pmer** [comment]
Oh, oops I didn't see the expired flickers code... so I ended up reimplementing it... c122279083f118d567537c95693bb46d822f6369. 😅

**Comment by pmer** [comment]
I tried reverting 37a609577d48c42f485e1b4433632c0b095bf0bc but it didn't fix it.
