### ISSUE TITLE
Clean up duplicate code in WidgetManager

### ISSUE THREAD

**Issue by seisatsu** [seisatsu/Driftwood#81]
The container and text functions have a ton of duplicate code. It should be merged.

**Comment by pmer** [comment]
I think they would make good candidates for two new classes: ContainerWidget and TextWidget.

The base Widget class they derive from can contain the shared functionality.

What do you think?

**Comment by seisatsu** [comment]
Could work. I'll take a look at how I might want to do that.

**Comment by seisatsu** [comment]
As of abea37842bc16cfdfb14168966b99604757ea48a we've probably done most of what we can reasonably do.
