### ISSUE TITLE
Pixel Mode Collisions

### ISSUE THREAD

**Issue by seisatsu** [seisatsu/Driftwood#9]
Calculate collisions with collision-enabled entities and unwalkable tiles in pixel movement mode.

**Comment by seisatsu** [comment]
Hey @pmer would you like to take a crack at this? You wrote the code for tile mode and it turned out alright.

**Comment by pmer** [comment]
I am a little hesitant to pick this up since IIRC the tile mode code was thought to be complicated & I don't want to have to maintain the movement code going forward if this one comes out complicated too.

**Comment by pmer** [comment]
Maybe that is just motivation for me to write really good, easy to read code though, hahah.

**Comment by seisatsu** [comment]
Alright I'll try to work it while keeping the logic as similar as possible.

---- On Fri, 14 Apr 2017 19:55:29 -0700 notifications@github.com wrote ----

I am a little hesitant to pick this up since IIRC the tile mode code was thought to be complicated & I don't want to have to maintain the movement code going forward if this one comes out complicated too.

**Comment by seisatsu** [comment]
Working on by-pixel movement now in pixel_collisions branch.

**Comment by seisatsu** [comment]
@pmer I was originally going to have the edge of an entity collide with the very edge of a tile, but I realized that this makes it almost impossible for a 1-tile-wide entity to fit through a 1-tile wide area. An alternative is to collide the center of an entity with the edge of a tile, which I think is what we should do. That's what I'll develop for now.

Check out the pixel_collisions branch.

**Comment by pmer** [comment]
Here's some techniques other games have used:

- Make players a few pixels smaller than a tile https://youtu.be/T08EidYtmT4?list=PL87EA9608EFE4BA83&t=716
- Bump the player left or right a few pixels when running into a corner if that will get them unstuck https://youtu.be/OWEvtPKany0?list=PLeZSRkjynvkvkZR5MKYtouNvX_8p2SP5N&t=354

**Comment by pmer** [comment]
Making players a few pixels smaller than a tile can be generalized to allow entities to be arbitrarily wide, which will be useful in the future for things such as projectiles (arrows, spells, etc).

**Comment by seisatsu** [comment]
Maybe. Let's keep the current solution for the time being. This issue is almost ready to close.

**Comment by pmer** [comment]
Made new issues for those.

**Comment by seisatsu** [comment]
Unfortunately, it looks like we also need to overhaul tile mode collisions so they play nice with pixel mode entities.

**Comment by seisatsu** [comment]
We do a lot of calculations with the _prev_xy variable and calculations in other places that may be totally unneeded now that I added the tile.offset() function to find a tile by xy offset. We were working with pixels in tile mode to find collisions.

**Comment by seisatsu** [comment]
I was able to improve turn mode collision using the new tile.offset() function, and also fix an unnoticed collision failure bug. In order for tile mode entities to check for collisions with pixel mode entities, I need to write a function that lists which tiles the pixel mode entity is partially on. Tile mode entities will not move to a tile if any part of a pixel mode entity is occupying it.

**Comment by seisatsu** [comment]
In 5678aee739bb6dac18e81ddefd6ff8caf67bc5b4 tile mode entities can detect collisions with pixel mode entities. Now I only need to write pixel to pixel collisions.
