### ISSUE TITLE
Support diagonal movement in pixel mode.

### ISSUE THREAD

**Issue by seisatsu** [seisatsu/Driftwood#90]
We will need to support moving in two directions at once before pixel mode is complete.

**Comment by pmer** [comment]
Here is an idea for a simple algorithm:

- Try moving one pixel up
- If success, try moving one pixel right
  - Try moving one pixel up
  - Return
- Else try moving one pixel right
- Return

**Comment by seisatsu** [comment]
This is actually a bit of a pain because InputManager wasn't written for it and since we use seconds_passed to calculate lengths of movement, if you try to alternate directions you just twitch in place. Can I ask you to take a look at this?

**Comment by seisatsu** [comment]
I'm bumping this to the next release.
