### ISSUE TITLE
Split player settings and author settings

### ISSUE THREAD

**Issue by pmer** [seisatsu/Driftwood#93]
Some engine settings should be player-controlled, such as:

- Window size & fullscreen
- Sound volume
- Keybindings

since these should match the preference of the player.

While others should be author-controlled, such as:

- Ticks per second
- Window title
- Logical viewport size

since these affect gameplay or the presentation of the game.

**Comment by seisatsu** [comment]
I disagree that the ticks per second should be author controlled. You may need to lower it on slow systems, especially during graphical effects.

There may be use cases for changing every setting the engine offers. That's why you can choose a configuration file at the command line. Authors should ship their own with their game data. Eventually we should make a graphical launcher though.

**Comment by seisatsu** [comment]
Authors should be able to add widgets to their game to let you change things like the volume and save those settings to disk.

**Comment by pmer** [comment]
Ooh, good point. Actually, since ticks per second is a technical problem that can be automated we should do that. Decrease it when the frame rate drops below max, and increase it otherwise.

Widgets sound good. 👌

Changing the logical viewport size allows you to see the whole area at once, which can be cheating unless the game author specifically thinks about this when making every area. Not sure if we want to build that capability into the engine?

**Comment by pmer** [comment]
Another possibility is to make changing the zoom level really easy, to give the hint to authors that a player can do this at any time.

E.g., we can recommend keybindings of '+' and '-' to increase and decrease zoom level at runtime.

**Comment by pmer** [comment]
In Yume-Nikki if you could see 3x further away it would change the feel of the game because you would not feel as lost.

**Comment by pmer** [comment]
To me, the logical viewport size is an integral part of the emotional experience of a game. An author should be allowed to fix it to a certain size, or control it dynamically with software in response to events, but a player should not be able to control it.

It makes about as much sense as allowing a player to change the colors & shading of any tree and building, or allow them to rewrite any character's dialogue.

**Comment by pmer** [comment]
If the logical viewport size is author controlled, the author may chose to allow a player to do this (perhaps limited to certain screens where it makes sense). They can add it to the game's on-screen settings dialog or as a keybinding like '+' and '-' mentioned above.

**Comment by seisatsu** [comment]
Auto-tuning the tps is an interesting idea.

As for author settings, I'm not sure what you think could be done to prevent the player from changing them. Only obfuscation could do this, and only for a little while. It's silly, like DRM. I think we should just let the author choose which settings to provide in-game dialogs for. Let the player ruin the experience for themselves if that's what they want.

We could have a default settings file in the game world, and then a player settings file that overlays on that, which is written from in-game dialogs.

**Comment by pmer** [comment]
Well, we obviously can't prevent the player from modifying the game 🙂 (since we ZIP everything up, technically *everything* is easy to change). This is just a place where I think it feels like we endorse it and we shouldn't.

I'm thinking we could move those settings to Python. As a bonus, this allows them to be changed during runtime in response to events.

**Comment by pmer** [comment]
DRM is defective and I am not advocating for that.

**Comment by seisatsu** [comment]
I guess we may want to initialize some window settings in python.

**Comment by pmer** [comment]
Great, I'll split this issue up.
