### ISSUE TITLE
Support changing speed of pixel-mode entities.

### ISSUE THREAD

**Issue by seisatsu** [seisatsu/Driftwood#95]
Currently, pixel-mode entities move at an arbitrary speed which is probably bound to the tps setting. We need to be able to lower the speed or raise it past one pixel per tps with some mathemagic.

**Comment by pmer** [comment]
Speed should be measured in distance per unit time.

**Comment by seisatsu** [comment]
I think we measure tile mode entities in pixels per second, so we should do the same for pixel mode entities.
