### ISSUE TITLE
Auto-regulate ticks per second

### ISSUE THREAD

**Issue by pmer** [seisatsu/Driftwood#96]
Decrease the ticks per second as the frame rate drops, and increase it back when the frame rate rises.

**Comment by seisatsu** [comment]
We will auto-regulate if tps is set to 0. Otherwise it's a manual setting.

**Comment by pmer** [comment]
Or if it's absent.

**Comment by seisatsu** [comment]
I don't think we allow settings to be absent currently.

**Comment by pmer** [comment]
Oh, cool.

**Comment by seisatsu** [comment]
You seem to have an idea of how this would work, so I'd like if you could work on it.

**Comment by pmer** [comment]
@seisatsu Just wondering. Do we even need to limit TPS since we always request vsync to be on? I'm wondering if that will limit TPS to the refresh rate of the screen.

**Comment by seisatsu** [comment]
I'm not sure. It may just run as fast as it's able.

**Comment by pmer** [comment]
Yes, of course. But if vsync is turned on then SDL_RenderPresent() will pause the process every frame until the vertical synchronization of the monitor.

**Comment by pmer** [comment]
The other thing to consider is that some gamers like to turn off vsync and run games at maximum frame rates (e.g., 300 fps) because this minimizes input lag which improves your performance in twitch-heavy games.

**Comment by pmer** [comment]
Let's assume vsync will always work for now and reopen this issue if it becomes a problem.
