### ISSUE TITLE
Walking in pixel mode stutters when interact key is held.

### ISSUE THREAD

**Issue by seisatsu** [seisatsu/Driftwood#98]
Something about the movement or input handling causes walking to become choppy if the interact button is pressed or held while walking. Other graphics are not affected.

**Comment by seisatsu** [comment]
The issue suddenly vanished. However, walking in tile mode while pressing or holding the interact button seems to have some undefined behavior that can even cause the engine to stop running.

**Comment by seisatsu** [comment]
I think we're causing weird issues in InputManager as a walk button and the interact button compete for the top of the input stack.

**Comment by seisatsu** [comment]
I found that this is still happening.

**Comment by pmer** [comment]
Looks like the FPS drops down to the `afps` of the entity's stance.

**Comment by pmer** [comment]
Fixed.
